version: '3.8'
networks:
  app-network:
    driver: bridge
services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - app-network  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "tracking-app"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
  